name: frontend-pages

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-pages.yml"
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-pages.yml"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    outputs:
      artifact_path: ${{ steps.upload.outputs.artifact_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: pm
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "pm=pnpm" >> "$GITHUB_OUTPUT"
          elif [ -f yarn.lock ]; then
            echo "pm=yarn" >> "$GITHUB_OUTPUT"
          else
            echo "pm=npm" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: ${{ steps.pm.outputs.pm }}

      - name: Enable Corepack (pnpm/yarn)
        run: corepack enable

      - name: Install deps
        run: |
          if [ "${{ steps.pm.outputs.pm }}" = "pnpm" ]; then
            pnpm i --frozen-lockfile
          elif [ "${{ steps.pm.outputs.pm }}" = "yarn" ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi

      - name: Build
        env:
          # VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          # VITE_SOME_KEY: ${{ secrets.VITE_SOME_KEY }}
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          if [ "${{ steps.pm.outputs.pm }}" = "pnpm" ]; then
            pnpm build
          elif [ "${{ steps.pm.outputs.pm }}" = "yarn" ]; then
            yarn build
          else
            npm run build
          fi

      - name: Upload artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          # Default output Vite adalah "dist"; sesuaikan kalau kamu ubah
          path: frontend/dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
